// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHfTtiVONNQa9-VGBcvt8x_7TDBCTA8PM',
    appId: '1:812890292702:web:6163cdb83e968e9e23dd4f',
    messagingSenderId: '812890292702',
    projectId: 'hotelhubb-2f57e',
    authDomain: 'hotelhubb-2f57e.firebaseapp.com',
    storageBucket: 'hotelhubb-2f57e.appspot.com',
    measurementId: 'G-HJCG52933W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM4F2dWSy4izN1fh9d_Q_cbGbRpBkHXRg',
    appId: '1:812890292702:android:452a7b4b7c54aa2123dd4f',
    messagingSenderId: '812890292702',
    projectId: 'hotelhubb-2f57e',
    storageBucket: 'hotelhubb-2f57e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmLRSE6zYgyhMbEen8vc4scfp3kN5WyWU',
    appId: '1:812890292702:ios:919fec2f1555202123dd4f',
    messagingSenderId: '812890292702',
    projectId: 'hotelhubb-2f57e',
    storageBucket: 'hotelhubb-2f57e.appspot.com',
    iosBundleId: 'com.example.hotelhubb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmLRSE6zYgyhMbEen8vc4scfp3kN5WyWU',
    appId: '1:812890292702:ios:e120185982e4a66a23dd4f',
    messagingSenderId: '812890292702',
    projectId: 'hotelhubb-2f57e',
    storageBucket: 'hotelhubb-2f57e.appspot.com',
    iosBundleId: 'com.example.hotelhubb.RunnerTests',
  );
}
